[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist/spa"

[build.environment]
  MONGODB_URI = "mongodb+srv://Hammad:Soomro@cluster0.bqlcjok.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
  MONGODB_DB = "teamwork"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"